# Generated by Django 5.2.6 on 2025-12-02 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('street_address', models.CharField(max_length=50, verbose_name='Street Address')),
                ('country', models.CharField(choices=[('us', 'United States'), ('uk', 'United Kingdom'), ('uae', 'United Arab Emirates')], max_length=50, verbose_name='Country')),
                ('state', models.CharField(choices=[('ny', 'New York'), ('al', 'Alabama'), ('ak', 'Alaska')], max_length=50, verbose_name='State')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address Book',
                'verbose_name_plural': 'Address Book',
            },
        ),
    ]
