# Generated by Django 5.2.6 on 2025-12-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='is_default_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='is_default_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
