# Generated by Django 5.2.6 on 2025-12-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0002_addressbook_is_default_billing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='is_default_billing',
        ),
    ]
