# Generated by Django 5.2.6 on 2025-09-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productgallery_productvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='url_title',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='url_title',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
