# Generated by Django 5.2.6 on 2025-12-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_productreview_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
