# Generated by Django 5.2.6 on 2025-12-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Show on home'),
        ),
    ]
