# Generated by Django 5.2.6 on 2025-12-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_productcategory_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='Image'),
        ),
    ]
