# Generated by Django 5.2.6 on 2026-01-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Footer Link Box',
                'verbose_name_plural': 'Footer Link Box',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('site_url', models.CharField(max_length=100, verbose_name='Site URL')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('fax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fax Number')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('about', models.CharField(max_length=100, verbose_name='About')),
                ('copyright', models.CharField(max_length=100, verbose_name='Copyright')),
                ('site_logo', models.ImageField(upload_to='images/settings', verbose_name='Site Logo')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('url', models.URLField(max_length=300, verbose_name='URL')),
                ('FooterLinkBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_module.footerlinkbox', verbose_name='Footer Link Box')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Link',
            },
        ),
    ]
