# Generated by Django 5.2.6 on 2025-12-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_delete_wishlist'),
        ('wishlist_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_wish', to='product_module.product', verbose_name='Product'),
        ),
    ]
