# Generated by Django 5.2.6 on 2025-11-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
            preserve_default=False,
        ),
    ]
