# Generated by Django 5.2.6 on 2025-11-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0002_cart_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
    ]
