# Generated by Django 5.2.6 on 2025-10-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0003_blogtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(related_name='blogs', to='blog_module.blogtag', verbose_name='Tags'),
        ),
    ]
