# Generated by Django 5.2.6 on 2025-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='ClientsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('image', models.ImageField(upload_to='images/clients_feedback', verbose_name='Image')),
                ('text', models.TextField(verbose_name='Text')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Clients Feedback',
                'verbose_name_plural': 'Clients Feedback',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('image', models.ImageField(upload_to='images/team_member', verbose_name='Image')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
